apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: erpao5boj-go 
  janus-idp.io/tekton: erpao5boj-go
  backstage.io/kubernetes-id: erpao5boj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: erpao5boj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml